### ISSUE TITLE
Feature request: combined color and ocean maps

### ISSUE THREAD

**Issue by seanth** [Sigma88/Sigma-Cartographer#21]
There's no good output map type that can be used by Kopernicus in scaledSpace. There would need to be a combination of the colourMap and the oceanMap.

I propose a new map output option that does exactly that. I'm not sure what the best name for it would be. Maybe something as simple as PQSMap.

I can't compile the code to test this, but it seems like after including the bits to check whether the user wants to map type output, all you'd need is something like

                                if (exportPQSMap)
                                {
                                    CreateSatelliteMap(ref colorMap, ref oceanMap, ref satelliteMap);
                                    ExportPQSMap(ref satelliteMap, subfolder + "PQSMap/", fileName);
                                }

**Comment by Sigma88** [comment]
what you need is:
```
@SigmaCartographer
{
	Maps
	{
		body = Kerbin
		width = 4096
		tile = 4096
		flipH = true
		oceanFloor = false
		colorMap = true
	}
}
```



`name = Kerbin` should have the name of the planet you want to export

`width = ` and `tile =` should be equal so that you get a single texture, the number is how many pixel you want in the long side of the texture

`flipH = true` is necessary because KSP applies textures flipped horizontally for some reason

`oceanFloor = false` makes sure the ocean surface is printed instead than the ocean floor

`colorMap = true` makes sure the color map is exported

you can also add `normalMap = true` to export the normals (still needed for scaled space)

finally, if you don't like the color of the ocean that is automatically chosen by Cartographer you can override it by adding

`oceanColor =` and whatever color you want

**Comment by seanth** [comment]
Perfect. I knew about oceanFloor = false, but didn't think to try it.

EDIT: that worked great. This can be closed, me thinks
